"""empty message

Revision ID: 0dabec2b6249
Revises: 9493c1f46448
Create Date: 2022-03-08 15:36:39.814846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dabec2b6249'
down_revision = '9493c1f46448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'movieDB', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'movie_id')
    # ### end Alembic commands ###
