"""empty message

Revision ID: 76147cead493
Revises: 0dabec2b6249
Create Date: 2022-03-08 16:06:05.682198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76147cead493'
down_revision = '0dabec2b6249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_movie_id', 'review', 'movieDB', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'movie_id')
    # ### end Alembic commands ###
