"""constraint

Revision ID: 9e05cf16b9e3
Revises: de54aba3efeb
Create Date: 2022-03-08 16:39:44.918527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e05cf16b9e3'
down_revision = 'de54aba3efeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_movie_id', 'movieDB', ['movie_id'], ['movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
